name: Run OCR on PDFs

on:
  workflow_dispatch:
  push:
    paths:
      - "samples/**"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system OCR deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run the batch extractor
        run: python batch_extract.py

      - name: Commit outputs back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs
          git commit -m "Add OCR outputs" || echo "No changes to commit"
          git push
