name: Run OCR → OpenAI → Outputs

on:
  workflow_dispatch:        # run manually from the Actions tab
  push:                     # also run when PDFs/images are added/changed
    paths:
      - "samples/**"

permissions:
  contents: write           # needed so the workflow can commit outputs back

concurrency:
  group: ocr-openai-${{ github.ref }}
  cancel-in-progress: true  # avoid overlapping runs

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      # === mode & OpenAI config ===
      EXTRACTOR_MODE: OPENAI
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # set this repo secret!
      # Optional tuning (you can leave these out)
      OPENAI_MODEL: gpt-5
      OPENAI_MAX_ATTEMPTS: "8"
      OPENAI_BASE_SLEEP: "2.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo tree (before)
        run: |
          echo "Repo tree BEFORE:"
          ls -R || true
          echo "samples/ listing:"
          ls -l samples || true

      - name: Install system OCR deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install httpx==0.27.0

      - name: Run batch extractor (OCR → LLM → Outputs)
        run: |
          mkdir -p outputs/json
          python batch_extract.py
          echo "Repo tree AFTER:"
          ls -R || true

      - name: Commit outputs back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -d outputs ] && [ -n "$(ls -A outputs || true)" ]; then
            git add outputs
            git commit -m "Add LLM OCR outputs" || echo "No changes to commit"
            git push
          else
            echo "No outputs to commit."
          fi

